### ISSUE TITLE
Association page without any information

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform_issues#1]
_From @nikiforosk on January 13, 2017 14:41_

The following associations page is empty:

https://www.targetvalidation.org/disease/GO_0002445/associations

This may be because there are no targets associated with this disease (type II hypersensitivity) or because this is a GO term.
![empty-page-go_0002445-associations-1484317468566](https://cloud.githubusercontent.com/assets/20280139/21933712/60614d36-d99e-11e6-9676-740bcb28e093.png)

_Copied from original issue: opentargets/features#38_

**Comment by elipapa** [comment]
_From @emepyc on January 13, 2017 14:47_

It is a disease ID, but we don't have the same empty response for diseases without associations as we have for the unknown targets.
I'll add one.
We should also try to differentiate between unknown disease IDs and diseases without targets associated.

**Comment by elipapa** [comment]
_From @nikiforosk on January 13, 2017 15:12_

Thanks! 

The problem here is that one cannot easily go from the associations page to the disease page:
https://www.targetvalidation.org/disease/GO_0002445

Also on the associations page we should mention that there are no targets associated with this disease

**Comment by elipapa** [comment]
_From @emepyc on January 13, 2017 15:14_

Yes, the overview page should help with that

**Comment by emepyc** [comment]
This is already fixed and deployed in production
