### ISSUE TITLE
Can you please add download image button to the expression atlas?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#16]
Got back to the user after discussing this with @emepyc and said: we should be able to add a "download image button" to the Expression Atlas image. The download will not include the legend or the diagram of the human body, just the heatmap. For the full capture of what they see in the Platform, screenshot would be the quickest way forward at the moment as we do not have much control on the image (code or data) ourselves.

**Comment by deniseOme** [comment]
The original user request was: "is there a way for me to pull the articles from your Europe PMC Text mining for a particular gene/target combination? For example via a static web link or the open targets API".

**Comment by elipapa** [comment]
when we make our own widget https://github.com/opentargets/features/issues/47 we'll offer a download.

**Comment by elipapa** [comment]
![image](https://user-images.githubusercontent.com/112610/34880527-a612d614-f7a8-11e7-866a-37541142b338.png)
