### ISSUE TITLE
Odds ratios instead of (in addition to) log2 fold change?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#17]
Comment that for germline SNPs' association w/ a disease, OR can be much more dramatic.

e.g. OR for COL11A1 in breast cancer is >30 but it isn't picked up in expression studies

**Comment by elipapa** [comment]
only data we have for this connection is expression atlas RNA expression and log2 change is most intuitive for that.

clarification?

**Comment by deniseOme** [comment]
This is all I've got:

**Comment by deniseOme** [comment]
https://twitter.com/targetvalidate/status/826058388886929409

**Comment by elipapa** [comment]
Issue moved to [opentargets/roadmap #135](https://github.com/opentargets/roadmap/issues/135) via [**ZenHub**](https://www.zenhub.com/)
