### ISSUE TITLE
European Clinical Trials Database

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#25]
Follow on a question at omics data integration: is it worth curating drug information from the European Clinical Trials Database? What are the differences when compared to clinicaltrials.gov or daily med?

https://eudract.ema.europa.eu/

**Comment by iandunham** [comment]
One to ask Chembl about.

**Comment by ckongEbi** [comment]
@elipapa can you move this to data-providers repo https://github.com/opentargets/data-providers-docs/issues, i take it up with ChEMBL

**Comment by elipapa** [comment]
Issue moved to [opentargets/data_release #54](https://github.com/opentargets/data_release/issues/54) via [**ZenHub**](https://www.zenhub.com/)
