### ISSUE TITLE
HLA genes removed from GWAS

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#28]
Followed Takeda's hands on and Ian McLean's question, HLA associations seem to be missing from the Platform as they get removed from GWAS.

Can this information be retrieved by other means? Why aren't they picked up by text mining. Could UniProt look at these papers and curate them? 

If there are no other way, I’d be interested in curating some of this evidence (from papers etc), if necessary.

@nikiforosk @iandunham

**Comment by deniseOme** [comment]
could @MayaGhoussaini come up with a list of HLA genes from papers and we see how text mining is picking that up?

**Comment by deniseOme** [comment]
@MayaGhoussaini has compiled a list of diseases where genes in the MHC (e.g. HLA) have been implicated.

[MHC_Diseases.xlsx](https://github.com/opentargets/platform_issues_triage/files/973109/MHC_Diseases.xlsx)

**Comment by deniseOme** [comment]
@iandunham, @MayaGhoussaini will have a look at this list and state whether or not the association is in the Platform. If so, she will also note which evidence is available (from GWAS, text mining, etc..).

**Comment by ckongEbi** [comment]
@MayaGhoussaini it will be useful to have the publication id and we can follow up with epmc. Have a quick look at the list, in this example we do have HLA association, but not the genes from the list provided.

![image](https://cloud.githubusercontent.com/assets/6169985/25747511/9f2ce9c2-319f-11e7-8ae0-9ea86bdb6d5e.png)

![screen shot 2017-05-05 at 14 30 00](https://cloud.githubusercontent.com/assets/6169985/25747452/716ee4a4-319f-11e7-9b0c-ff856722e540.png)

**Comment by elipapa** [comment]
Issue moved to [opentargets/roadmap #134](https://github.com/opentargets/roadmap/issues/134) via [**ZenHub**](https://www.zenhub.com/)
