### ISSUE TITLE
Replacing 'Genetic Associations' by 'Genetic Evidence'? 

### ISSUE THREAD

**Issue by MayaGhoussaini** [opentargets/platform_issues#30]
@iandunham @elipapa @gkos-bio @emepyc @apierleoni 

Do you think it is possible to replace ‘Genetic Associations’ on the platform by ‘Genetic Evidence’ or something along those lines? I find that ‘Genetic associations’ can be confused with associations found through GWAS while the platform provides genetic links for both Common and Mendelian diseases.

**Comment by iandunham** [comment]
Definitely worth considering.  Although we could just go for "Genetics" as none of the other data types use the word association or evidence. Before doing anything, discuss with Niki to see what the background on how we got to associations is.

**Comment by MayaGhoussaini** [comment]
Sure. Thank you!

**Comment by elipapa** [comment]
Issue moved to [opentargets/roadmap #132](https://github.com/opentargets/roadmap/issues/132) via [**ZenHub**](https://www.zenhub.com/)
