### ISSUE TITLE
TBK1: protein expression on cortex, but not brain?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#41]
This target is found to be highly expressed in the cortex (plus other regions of the brain) but in our table we say there is no expression in the brain: http://www.targetvalidation.org/target/ENSG00000183735

Looking at the original data from human protein atlas, it seems in their dumps they don't list brain but in their website they seem to combine all brain parts to say there is brain high protein expression:

http://www.proteinatlas.org/ENSG00000183735-TBK1/tissue

Isn't it misleading have brain as a row in the table saying it's not expressed at the protein level?
<img width="659" alt="screen shot 2017-10-23 at 18 20 39" src="https://user-images.githubusercontent.com/6472381/31902991-a826815e-b81e-11e7-82f8-6ec499ad7b0a.png">

Any chance to clarify this somehow? Or leave 'brain' out?

**Comment by emepyc** [comment]
I think we get it right now:
https://expression-simple--paratrooper-antelope-70721.netlify.com/target/ENSG00000183735

**Comment by iandunham** [comment]
I think @emepyc is saying we do show this now in the new interface (not released yet) 
[Untitled.tiff.pdf](https://github.com/opentargets/platform_issues/files/1410412/Untitled.tiff.pdf)

**Comment by deniseOme** [comment]
Ooops. I did not realise we could click on brain (or other organ) and get its components...
Now I know we can. Thanks for that.

**Comment by deniseOme** [comment]
Btw, this is amazing @emepyc!

**Comment by emepyc** [comment]
Thanks, but credits go to @peatroot for developing it and @nikiforosk (and the rest of the team) for the design

**Comment by iandunham** [comment]
![untitled](https://user-images.githubusercontent.com/1729980/31939621-0827324e-b8b3-11e7-9620-8f1147dafae4.png)
