### ISSUE TITLE
spurious association between ENSG00000168077 and EFO_0000692

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#43]
Text mining has considered CSR as a synonym for SCARA3 but this paper

http://europepmc.org/abstract/MED/25786025

has CSR as "Clinical Severity Rating" rather than a gene name, hence the wrong association of CSR with the disease:

http://www.targetvalidation.org/evidence/ENSG00000168077/EFO_0000692

@ckongEbi @iandunham @elipapa @gkos-bio: can we include this in our "kill list" so that when we run our pipeline next time, this spurious association is no longer there?

Thanks,
Denise

**Comment by deniseOme** [comment]
We also should check all other TM results for SCARA3 as the following have been picked up by the user:

* Alzheimer's - CSR (Chronic Sleep Restriction)
* Genetic disorder - CSR (Class-switch recombination  or Corporate Social Responsibility)
* Heart disease - CSR = Cheyne-Stokes-respiration or cumulative social risk

**Comment by iandunham** [comment]
@ckongEbi Can you have a discussion about filtering these and the other false positives we identified from the Text mining feed. We should either do this together with EuroPMC or add our own filters. 

Add in all the false positives from the integration day

**Comment by elipapa** [comment]
not sure we have a "kill list" .. do we?

**Comment by iandunham** [comment]
There's a set of filters in Senay's code for this type of case. Obviously we need to build a long term solution, but we also should see if we can fix these short term. One way to do it short term would be to use this information and the false positives from the integration day to identify papers that we know are FPs and throw them out.

**Comment by ckongEbi** [comment]
I can speak to EPMC with a list of FP list and discuss the possibility of them filtering these out for the short term.  Initial list here:
https://docs.google.com/spreadsheets/d/1RiYCYdD-XHPbEszQKsZvKkC2Y2utAKNj9oC_YgpWEeU/edit?usp=sharing

@iandunham do you have the post-Integration day list from epmc somewhere, I can't seem to locate them..

**Comment by elipapa** [comment]
Issue moved to [opentargets/epics #123](https://github.com/opentargets/epics/issues/123) via [**ZenHub**](https://www.zenhub.com/)
