### ISSUE TITLE
include the biogps static images for human expression data of the gene of interest with a link to biogps.

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform_issues#8]

**Comment by elipapa** [comment]
overall biogps website: http://biogps.org/#goto=genereport&id=4261 

specific link that has images to download: http://ds.biogps.org/?data set=BDS_00001&gene=4261

**Comment by emepyc** [comment]
If the data behind biogps is not in our platform I don't see the point of linking to their images.
This will be solved when we have our own widget for expression

**Comment by deniseOme** [comment]
But we link to other images without having their data (e.g. GTEx, PDBe)?!?!?

**Comment by emepyc** [comment]
I don't mean we don't have their data in the backend, but in the webapp.
For gtex, we import the data (from their rest api), and display it in our webapp, then we link to the external source for more details.
The same happens for PDBe, we show the structure in our site, we link out for more details.

This issue is asking just for a link to an external image in an external site without any context on our end. For me it is a very different case.

**Comment by emepyc** [comment]
Bear in mind that from the webapp user point of view, if the data comes from our backend or from an external rest api is transparent to them. For what they can tell, the data is just there in our site.

**Comment by elipapa** [comment]
It is possible in principle to build an url such as http://ds.biogps.org/?dataset=GSE1133&gene=4261
since we do provide the DB xrefs to the NCBI gene id. 

For instance:
```sh
http 'https://www.targetvalidation.org/api/2.0/private/target/ENSG00000179583' | jq '.dbxrefs' | grep 'GeneID'
```
returns 
```sh
  "GeneID:4261",
```

However the links goes to an html page, rather than a static image. The image asset is not immediately available with a direct http call.

I think we would need to first:
- [ ] find out if exp atlas already includes these datasets
- [ ] if not included, probably import the downloadable datasets in our backend http://biogps.org/downloads/

**Comment by elipapa** [comment]
@ckongEbi will ask exp atlas if the data overlaps with their baseline submission to us.

**Comment by ckongEbi** [comment]
@elipapa can you move this to data-providers repo https://github.com/opentargets/data-providers-docs/issues, i take it up with ChEMBL

**Comment by elipapa** [comment]
Issue moved to [opentargets/data_release #56](https://github.com/opentargets/data_release/issues/56) via [**ZenHub**](https://www.zenhub.com/)
