### ISSUE TITLE
quantitative data for genes on which cell types they are expressed in

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform_issues#9]
> I'd like to see quantitative data for genes on which cell types they are expressed in. For example, "Gene A" is expressed highly in "Cell type B" but not at all in "Cell type C".

**Comment by elipapa** [comment]
Quantitative expression data could be extracted from http://www.im mgen.org/databrowser/index.html for lymphocytes and http://servers .binf.ku.dk/bloodspot/ for other blood cells

**Comment by elipapa** [comment]
compare with expression atlas

**Comment by ckongEbi** [comment]
@elipapa can you move this to data-providers repo https://github.com/opentargets/data-providers-docs/issues, i take it up with ChEMBL

**Comment by elipapa** [comment]
Issue moved to [opentargets/data_release #55](https://github.com/opentargets/data_release/issues/55) via [**ZenHub**](https://www.zenhub.com/)
